### ISSUE TITLE
Process KILLED

### ISSUE THREAD

**Issue by OumaimaHamza** [josefin-werme/LAVA#15]
I'm getting the following message while running LAVA :
![244502723_403030994566277_6794801050323699197_n](https://user-images.githubusercontent.com/73792407/135790524-c76f6de7-a739-49fc-899c-aafd7d6e22ee.png)
it's the same example from the tutorial ,  i am running it on Ubuntu 
Is this a known issue ? how can I solve it ? thanks !

**Comment by josefin-werme** [comment]
Hi, 

It seems like it's being killed by the system at the point of reading in the sumstats. I don't know what kind of sumstats files you have but this shouldn’t normally require more than 4-5Gb memory for two phenotypes. If you have access to a cluster computer I would recommend setting up your analyses there, at least for whole-genome analyses. 

Best,

Josefin
