### ISSUE TITLE
Read a group of loci at a time

### ISSUE THREAD

**Issue by Iago-Junger** [josefin-werme/LAVA#18]
Hello, dear all! How are you? Hope you're all fine

I wanted to run bivar and univ LAVA by just running the loci that comprehend the CHR 5. In this line of code below, we select all the loci by using nrow(loci), is there a way to select just a bunch of loci? (in my case, from locus 775 to 925). Thank you for trying to help :)

### Read in data
loci = read.loci(loc.file); n.loc = nrow(loci)

All the best, 

Iago

**Comment by josefin-werme** [comment]
Hi! 

If you only want to analyse the loci on chr5 I would probably just subset the whole locus file on read in:

loci = subset(read.loci(loc.file), CHR==5); n.loc = nrow(loci)

Hope this helps! 

Josefin
