### ISSUE TITLE
"Error: Locus info data frame is missing some or all of the required headers ('LOC' + 'CHR','START','STOP' and/or 'SNPS')"

### ISSUE THREAD

**Issue by IsabelaVelloso** [josefin-werme/LAVA#23]
Hi there,

I'm having this issue where a try to prepare de locus for analysis, but, even with my data with all headers in CAPS and all separated by white space, it does not recognize it in the process.locus command. Can someone help?
![Sem título](https://user-images.githubusercontent.com/81487259/167459540-4b48c8e7-fd24-49b0-b420-c4d7c927fcfd.png)

**Comment by josefin-werme** [comment]
Hi,

Thank you for including a screenshot! It helps a lot :) 

It seems the files is being subsetted to row 40 and column 445 based on the call that I can see in the console: `process. locus (lociIGF1xTDAHDemontis [40,445] , inputIGF1xTDAHDemontis)`

Why this isn't throwing an error firstly about the column not existing Im not sure, but I would suspect this is what's causing the error with the function. As long as you just subset the file by row it should work!

Best, 

Josefin

**Comment by IsabelaVelloso** [comment]
Hi, thank you so much for your answer! 
I was thinking the numbers was the number of the specific loci I wanted to test, but it seems to be the number of the row, right? Now it worked! Thank you for the aid. 

Best regards,
Isabela.
