### ISSUE TITLE
devtools::install_github does not install vignettes

### ISSUE THREAD

**Issue by JoniColeman** [josefin-werme/LAVA#26]
Hi,

Just a note for the package, rather than an issue as such. 

Installing LAVA using devtools::install_github("https://github.com/josefin-werme/LAVA.git") does not (at least on my machine) install the "vignettes" folder. As such, one can only follow the tutorial if one downloads the repo separately. In which case, one might as well use 'devtools::install("~/Programs/R/LAVA")' instead.

As I said, not an issue as such - just a note for future users looking to run the tutorial.

**Comment by cadeleeuw** [comment]
Hi,

Thanks! It turns out that install_github has a build_vignettes parameter that is set to false by default, I updated the installation instructions to set this to true when running it.

Best,
Christiaan
