### ISSUE TITLE
Name causes problems with update.packages() and related functions

### ISSUE THREAD

**Issue by Pintaius** [josefin-werme/LAVA#3]
There seems to be another package in CRAN with the same name: https://cran.r-project.org/web/packages/lava/index.html

I only realised this when I tried to update my installed packages and saw:

> lava :
 Version 0.0.6 installed in C:/Research/Rlibs 
 Version 1.6.8.1 available at https://cran.revolutionanalytics.com

Not a major issue but could be problematic for users as any update operation which doesn't manually exclude this package will have it overwritten. I also checked `BiocManager::install()` and the same problem occurs. `dtupdate::github_update()` seems to be aware of the correct repository, but this function is not made to update CRAN/Bioconductor packages so is of limited use.

**Comment by josefin-werme** [comment]
Thank you for letting me know — I should have probably checked this before. 

I have now capitalised the package name to avoid this conflict.

**Comment by Pintaius** [comment]
Thank you Josefin for the speedy reply! I uninstalled the previous version with the conflicting name and installed the current one. No problems with `update.packages()` anymore!

**Comment by josefin-werme** [comment]
Thats great to hear! :)

Thanks again for letting me know — if you run into any other issues, please don’t hesitate to contact me. 

All the best, 

Josefin
