### ISSUE TITLE
Multiple regression analysis error message

### ISSUE THREAD

**Issue by actright7** [josefin-werme/LAVA#32]
Hi, I wanted to perform multiple regression analysis. I think everything was fine including strong and highly significant bivariate correlations estimates and p-values, respectively. However, multiple regression analysis came up with the following error message:
 "Genetic covariance matrix of predictor phenotyopes is not invertible".

I tried partial correlation between the outcome and two of the predictors at a time and none was significant, although the estimates were high and r2.phen1_z r2.phen2_z were not too different from each other. I recokon there is high multicolinearity between the traits.  

Please, can you help with this issue. How can this be resolved? Also, how can such results be interpreted?

Very many thanks for your help.

**Comment by cadeleeuw** [comment]
Hi,

In general, this does indeed sound like a collinearity issue, likely some of the genetic correlations between the predictor phenotypes are indeed just too strong. Could you give a screenshot of the genetic covariance and genetic correlation matrices (ie. the omega and omega.cor variables in the locus object returned from process.locus()), and indicate which was the outomce phenotype in your analysis?

Best,
Christiaan de Leeuw
