### ISSUE TITLE
Possibility to use a less strict P value threshold for univariate analysis

### ISSUE THREAD

**Issue by liviamotu** [josefin-werme/LAVA#38]
Dear LAVA team,
First, thank you for developing such an innovative and amazing method!

I'm wondering if it is possible to use a less strict P-value threshold in univariate analysis. I saw in the original tutorial, since 2495 LD regions were tested for univariate associations, the P-value threshold was set to 0.05/2495. I followed this first. Since my GWAS summary statistics only have 5 significant risk loci, it only resulted in 4 bivariate tests to be conducted and 1 significant rg. 
Then I used P value of 0.05, and it resulted in 71 bivariate tests conducted and 21 significant rg. 
Can I use a bigger p-value and does it make sense? If it's acceptable, how big the p-value could be?

Thank you in advance!

**Comment by cadeleeuw** [comment]
Hi,

In principle this is indeed possible, using a univariate threshold of 0.05/#regions is not a strict requirement or assumption for the analysis. Type 1 error rate control for the bivariate test is still maintained even when no threshold is used at all, though in practice I would at least keep it at a nominal 0.05. At very low univariate signal, power to detect local genetic correlations will be very low as well, and above a p-value of (approximately) 0.5 the variance estimates become negative and the bivariate analysis will return an NA p-value anyway.

Best,
Christiaan

**Comment by liviamotu** [comment]
Thanks a lot, Christiaan!
I got it.

Best
