### ISSUE TITLE
Unable to run with target phenotype if negative variance present in any loci. 

### ISSUE THREAD

**Issue by RubyWoodward** [josefin-werme/LAVA#44]
Hello,

I have been using LAVA for sometime now and managed to get it to run fairly smoothly! 

I am currently doing an analysis which requires me to run the run.univ.bivar function with a target phenotype (to avoid calculating correlations for all possible pairs), however, as soon as I get a warning (as seen below) for the target phenotype specified, the entire job is halted and cancelled.

Warning: Negative variance estimate for phenotype(s)

I have attempted (with no avail) to add a 'next' into the if loop, hoping to bypass the current script:
if (! target %in% locus$phenos) { print(paste0("Error: Invalid target phenotype specified: '", target,"'")); return(NULL) }

I was wondering if this was purposeful, and to what reason if a locus is removed due to negative variance, the whole process is cancelled - or if there is something that can be added to the code to skip onto the next locus.

Thank you,

Ruby

**Comment by RubyWoodward** [comment]
Hello,

I have just reran my script with the editted code and getting this error: 
![image](https://github.com/josefin-werme/LAVA/assets/93588680/a66a8a71-b851-4e2a-bf2b-e1d5e2c5f0ea)
Which seems to be an issue much further up the line before even reaching what I have altered. 

Not too sure what has gone wrong here, used the original code and got the same error so must be something new for me, any idea? Once this is fixed I can test the "next" in loop theory, 

Thanks

Ruby

**Comment by cadeleeuw** [comment]
Hi,

That line of code is in the process.locus function. The max.K value is computed from the SNP sample size values in the N column (or the global N value if that column is not present), as such the most likely cause of this would seem to be that there are missing and/or non-numeric values in that column, in which case that if statement would indeed fail in this way. Does any of your input data indeed contain such a column, and if so are there any problem values in it?

Best,
Christiaan

**Comment by RubyWoodward** [comment]
Hello,

I managed to fix this error.
Although my original issue isn't quite fixed, I ended up running local genetic correlation between my two targe phenotypes against each other, and removed all loci that showed a negative variance estimate. Once I did this, the script ran fully, so I will close the issue.

Thank you for your help.

Ruby
