### ISSUE TITLE
Errors in the analysis of conditional genetic relations

### ISSUE THREAD

**Issue by zsf123525** [josefin-werme/LAVA#45]
Hello, 
   I recently used Multiple regression and Partial correlation to perform conditional genetic correlation analysis on multiple phenotypes. Unfortunately, I encountered into problems with the genetic variance matrix and bounds of estimates respectively. I would like to ask you for help for this reason  and  there a way to solve these problems?
   The error message is as follows:
> run.multireg(locus, target='AAA')
[1] "~ Running multiple regression for outcome 'AAA', with predictors 'CAD', 'MI'"
Error in run.multireg(locus, target = "AAA") : 
  Genetic covariance matrix of predictor phenotyopes is not invertible
> run.pcor(locus, target=c("AAA","CAD"), phenos='MI')
[1] "~ Running partial correlation for 'AAA' and 'CAD', conditioned on 'MI'"
Warning: Estimates too far out of bounds (+-1.25) for phenotype(s) MI ~ CAD (3.733) in locus 112. Values will be set to NA. To change this threshold, modify the 'param.lim' argument
Error in if (all(out[c("r2.phen1_z", "r2.phen2_z")] < max.r2) & p.values) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In sqrt(partial.var(omega, x, z) * partial.var(omega, y, z)) :
  NaNs produced
![Snipaste_2023-05-27_16-13-40](https://github.com/josefin-werme/LAVA/assets/82014973/6c9c36ef-a76a-4451-8da2-9b912ab9e09c)

Thank you,

Shufen

**Comment by cadeleeuw** [comment]
Hi,

The problem in this case is that the estimated correlation between CAD and MI is essentially 1, creating an extreme collinearity in the regression model (ie. a singularity). Hence the message about invertability. 

Partial correlation would run in more or less the same issue, if in a slightly different form. In this case the "out of bounds" error prevents the partial correlation analysis from proceeding further, but this would have ended up giving you a message about the residual variance of MI after conditioning on the covariates being too small. That is, MI would explain all of the variance in CAD, so there is nothing left to correlate with (the residual of) AAA.

In this case there also seems to be somewhat of an instability in the CAD - MI correlation, hence the other errors, but fundamentally this is a data issue: as far as the input data can tell us, the genetic signals between CAD and MI in this locus are indistinguishable. 

Partly, this may be a power issue, with larger samples and a resultingly more stable and accurate estimate, it may turn out that the correlation estimate would be found to be smaller than one, in which case it would be possible to run these regression/partial correlation models, but with the given data that unfortunately isn't an option.

Best,
Christiaan

**Comment by zsf123525** [comment]
okay,Thank you very much for your answer! @cadeleeuw
