### ISSUE TITLE
Regarding sample size for case -control GWAS 

### ISSUE THREAD

**Issue by karpat90** [josefin-werme/LAVA#51]
Hello!

I wanted to ask if similar to ldscr, I should use an effective sample size instead of regular N=n cases+n controls  for case-control GWAS in LAVA analyses?

Many thanks for your wonderful program!

**Comment by cadeleeuw** [comment]
Hi,

For LAVA, we would recommend just using the regular N, without adjustments.

**Comment by karpat90** [comment]
Thank you!
So Number of cases + number of controls will be sufficient? In my data, I use total sample size which does not vary per SNP because I don't have this information

**Comment by cadeleeuw** [comment]
Yes, that should be sufficient.
