### ISSUE TITLE
Model does not converge

### ISSUE THREAD

**Issue by karpat90** [josefin-werme/LAVA#52]
Hello!

I am using UKBB data with 104 cases and 456244 controls for Phen1. The data doesn't have any genome-wide significant SNPs.

When I try running the analyses I get an error:
Multiple logistic regression model for phenotype 'Phen1' in locus 1740 failed to converge (inversion error)

I have tried with another locus and I get the same error.

Could you help me with this?

Thank you!

**Comment by ancolococky** [comment]
So, how was this error solved? I am also tackling the same issue. I will really appreciate it if anyone could provide a solution. Thanks!
