### ISSUE TITLE
Partial correlations

### ISSUE THREAD

**Issue by NicolasC0** [josefin-werme/LAVA#53]
Hello Josefin,

Thank you for developing LAVA! 

I have a question concerning partial correlations. I ran the univariate and bivariate analysis for two traits and picked up a couple of significant loci and I'd like to test a partial correlation between them conditioned on a third trait. I was wondering whether, for each individual locus, I should only run a univariate analysis, check if there is enough heritability for the third trait and move straight on to the partial correlations, or if it is best to also run a bivariate analysis between my initial traits of interest and the third trait (and check if there is a significant correlation for the locus).

Best regards,

Nicolas

**Comment by josefin-werme** [comment]
Hi Nicolas,

I would definitely check that there are also bivariate correlations with the third trait as well. Conceptually, if the third trait isnt correlated with the two others, there is no reason to hypothesise that it might explain the correlation between them. 

Best, 

Josefin

**Comment by NicolasC0** [comment]
Thank you for the clarification! :)

Best,

Nicolas
