### ISSUE TITLE
Ref: Model does not converge #52

### ISSUE THREAD

**Issue by ancolococky** [josefin-werme/LAVA#54]
So, how was this error solved? I am also tackling the same issue. In my case, the error occurred for some loci but not for other loci. I will really appreciate it if anyone could provide a solution. Thanks!

https://github.com/josefin-werme/LAVA/issues/52#issue-1804890626

**Comment by cadeleeuw** [comment]
This issue can arise if there is an extreme skew in the case-control ratio, or sometimes if there is an extreme amount of genetic signal for that phenotype in that region. Do either of these apply to your input data for those loci?

**Comment by ancolococky** [comment]
Hi cadeleeuw, 

Thank you very much for your reply. 

I am measuring the genetic correlations among three groups with different traits.
Those traits are genetically correlated at a global level. 

The case-control ratios are skewed towards the cases in all the groups:
trait1 0.0127 
trait2 0.0178 
trait3 0.0577 
If these skewnesses matter, the model conversion issue would happen to all the loci and the traits tested, so I guess this is not the critical reason.

The numbers of signals in each locus for all the traits tested are as below. 
Locus# | Trait 1 | Trait 2 | Trait 3
1 | 7715 | 7701 | 9288
2 | 4453 | 4386 | 6235
3 | 6175 | 6069 | 8153
4 | 7299 | 7113 | 10093
5 | 6699 | 6593 | 8603
6 | 7536 | 7581 | 9680
7 | 7657 | 7653 | 10559
8 | 6888 | 6879 | 9120
9 | 6570 | 6626 | 8569
10 | 5768 | 5548 | 7325  <- Inversion error in Trait 1
11 | 6813 | 6597 | 8522
12 | 7408 | 7223 | 9596
13 | 6121 | 6429 | 6811
14 | 10135 | 10033 | 12428

Although the numbers of signals in Trait3 are larger than the other two in all the loci, the issue seems not to come from the differences.

Thanks for your help.
