### ISSUE TITLE
vignettes/data/data/asthma.sumatats.txt can not be shown

### ISSUE THREAD

**Issue by XuanxiaoLi** [josefin-werme/LAVA#57]
Hi, I am trying to check the asthma.sumatats.txt, but when I click on it, the words that  can't show the file appear.I want to know  the information about the asthma.sumatats.txt. Thanks!

**Comment by cadeleeuw** [comment]
Hi,

This is just a limitation of the Github interface, it doesn't show the content of files if they are beyond a certain size. To view the file, you need to download it first. You can either just download the entire LAVA package (on the main LAVA page, click the green Code button, then Download Zip), or to download just this file go to that file (ie. the page that give you this message) and click the download button on the right of the page (small down arrow). 

Christiaan

**Comment by XuanxiaoLi** [comment]
Thanks for your help！
