### ISSUE TITLE
HG38 BUILD LOCUS FILE

### ISSUE THREAD

**Issue by zara03** [josefin-werme/LAVA#67]
Hi
I am very new to these analysis.
I have summary statistics in Gh38 build and I want to perform LAVA. Where can i find locus file for Hg38 build?

**Comment by cadeleeuw** [comment]
Hi,

At present there is no locus file for GRCh38, you would need to create that either by lifting the genomic coordinates in the existing locus file over or running the partitioning tool on reference genotype data with GRCh38 coordinates. 

However, you likely do not need a GRCh38 locus file. The way LAVA works, is that SNPs are mapped to loci based on their genomic positions in the reference data, and summary statistics are then linked to that based on SNP IDs. Genomic positions in the input summary statistics files are never used, and as such it doesn't matter what build they are on. 

Best,
Christiaan de Leeuw

**Comment by cadeleeuw** [comment]
Yes, this is the main locus file we generally use with LAVA, as also in the original LAVA paper.
