### ISSUE TITLE
How to analyze all loci togather in R

### ISSUE THREAD

**Issue by zara03** [josefin-werme/LAVA#68]
I am trying to do LAVA in R.
I want to run all loci together as i have very big datasets, how to modify this code?so i can run all loci together?

locus = process.locus(loci[1,], input)

Thank you

**Comment by cadeleeuw** [comment]
Hi,

To run all loci, you can just use a for-loop to iterate over them. There is an example script at the bottom of the tutorial [here](https://github.com/josefin-werme/LAVA).

Best,
Christiaan
