### ISSUE TITLE
trouble processing loci for analysis

### ISSUE THREAD

**Issue by SBNeuro1** [josefin-werme/LAVA#76]
Hello again,

I'm having an issue running the process.locus command. I haven't had any luck troubleshooting this myself. This is the error:

Error in if (max.K < min.K) max.K = min.K : 
  missing value where TRUE/FALSE needed

I was having a read of another issue here:  https://github.com/josefin-werme/LAVA/issues/44

I'm wondering if this issue arises because of NA values in the rsID column in some of my sumstats?

Thanks!

**Comment by complexgenome** [comment]
Hi,
were you able to figure this out?

**Comment by SBNeuro1** [comment]
Hi complexgenome,

I ended up batch processing my sumstats to remove any row that contained NA values in a column that LAVA uses. This got my analysis running in the end.

**Comment by complexgenome** [comment]
@SBNeuro1 Thank you for your response. I do not ohave NA in the input summary statistics I provide in lava analysis.
