### ISSUE TITLE
GWAS dataset filtering for LAVA

### ISSUE THREAD

**Issue by zara03** [josefin-werme/LAVA#77]
Can we  use GWAS dataset without MAF given, i mean if we dont have MAF so with out filtering can we use that datasets for LAVA?
and should we use only significant SNPS or all the SNPs?

**Comment by josefin-werme** [comment]
Hi,

Yes, you can analyse sumstats that do not contain MAF. As noted in the tutorial, you only need: SNP ID, effect allele, reference allele, sample size, and either a Z score or effect size + p-value.

You should also include all available SNPs and not just the significant ones.

Best,

Josefin
