### ISSUE TITLE
about running mode and snps filtering

### ISSUE THREAD

**Issue by clauw87** [josefin-werme/LAVA#8]
Hi, Josefin
Thank you for the amazing work!
I am interested in using your software and as a test to learn how to use it I´m trying to reproduce the results in your paper with the 20 traits from GWAS atlas. I have not succeeded exactly; although I get similar results I dont obtain exactly the same numbers in: number of bivariate tests, loci, significant tests and significant loci and I think of two possible things that I might be missing that I would like to ask you:
1. I am prefiltering the SNPs from the sumstats to be analyzed to a list of 9M reliable snps from 1000G eur, but also tried to filter to the list of about 1M from hapmap3 that is used by ldsc, but was wondering if you have used a different list or, rather, not filtered the sumstats except by the INFO field as you mentioned in the methods
2. I am using the software in a "batch" mode analysing all 20 traits vs all by entering them all in the input.info file and not defining pheno parameter. But I have noticed that this limits the number of snps available to the common ones across the 20 traits while running a series of pairwise comparisons allow to leverage more snps in every pair and therefore gives more results, but I am wondering, which one of these two options have you used in the paper (and do you think the second one if a valid option provided that you adjust by the number of bivariate tests that are obtained at the end?)   
Thank you for your time!!
Best,
Claudia

**Comment by josefin-werme** [comment]
Dear Claudia, 

You are correct about the coding of CAD, the correct atlas ID actually 109! Note that there is also an error in the sample sizes that I reported for lupus in the same table, so please use those listed in the paper / on GWAS atlas (and not the ones in my table). I will make sure to correct these in the published version!

When you say you munge the sum-stats, you just mean you are subsetting them right? (And not that you will use the LDSC munged files in LAVA?). If the first, then that is fine. You also don't need to subset to g1000 SNPs btw as LAVA will do that internally, but it of course won’t hurt either. 

That is also the same SNP list I used for LDSC. But when you say you ran into an error when unfiltered for 1203, what do you mean by unfiltered? (And is that still an issue?)

All the other points look fine!

Best, 

Josefin
